import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from "../components/NavBar/NavBar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar></NavBar>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home
